#lang sicp
;; Exercise 1.9.
;; Each of the following two procedures defines a method for adding two positive integers
;; in terms of the procedures inc, which increments its argument by 1, and dec,
;; which decrements its argument by 1.

;; (define (+ a b)
;;   (if (= a 0)
;;       b
;;       (inc (+ (dec a) b))))

;; (define (+ a b)
;;   (if (= a 0)
;;       b
;;       (+ (dec a) (inc b))))

;; Using the substitution model, illustrate the process generated by each procedure in evaluating (+ 4 5).
;; Are these processes iterative or recursive?


;; (define (+ a b)
;;   (if (= a 0)
;;       b
;;       (inc (+ (dec a) b))))
(+ 3 5)
(inc (+ (dec 3) 5))
(inc (+ 2 5))
(inc
 (inc
  (inc
   (+ 0 5))))
(inc
 (inc
  (inc 5)))
(inc (inc 6))
(inc 7)
8
;; First one is recursive




;; (define (+ a b)
;;   (if (= a 0)
;;       b
;;       (+ (dec a) (inc b))))
(+ 3 5)
(+ (dec 3) (inc 6))
(+ 2 6)
(+ (dec 2) (inc 6))
(+ 1 7)
(+ (dec 1) (inc 7))
(+ 0 8)
8
;; This one is iterative
